language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"
  
script:
  - docker --version # print the version for logging
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed doananhduc/udagram-api-feed:v1
  - docker tag udagram-api-user doananhduc/udagram-api-user:v1
  - docker tag udagram-frontend doananhduc/udagram-frontend:v1
  - docker tag reverseproxy doananhduc/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push
  - docker push doananhduc/udagram-api-feed:v1
  - docker push doananhduc/udagram-api-user:v1
  - docker push doananhduc/udagram-frontend:v1
  - docker push doananhduc/reverseproxy:v1